### ISSUE TITLE
Understanding PayloadPark

### ISSUE THREAD

**Issue by rudh24** [PayloadPark/payloadpark#1]
Hi Swati,

Your CoNEXT 2020 paper, as well as the companion arxiv paper were super interesting reads! I am trying to understand your code. Although the paper does a great job of explaining how you go about striping the payload across the stages, I'm having trouble mapping the concept to your code. I would greatly appreciate any help that I can get in understanding your code! 

In the `single_pipe` implementation,
I can see that the [headers.p4](https://github.com/PayloadPark/payloadpark/blob/main/p4src/payload_park_single_pipe/headers.p4) defines 2 structures for the payloads `payload_t_block_0` and `payload_t_block_1`

I also noticed that these are read at 2 different places during the Ingress and Egress respectively, in the "split" operation.  Is this the tofino switch specific decision? Because the hardware resources are distributed among these stages in this manner?

Also, these payload structures add up to 20 + 144 bytes. I can't seem to figure out what the extra 4 bytes is for, since PayloadPark is supposed to store 160 bytes of the payload for all packets. What am I missing here?

Looking forward to your reply!

**Comment by sggoswam** [comment]
Thanks for reaching out.

Using two structures was a Tofino specific decision. I didn't see much of a point in trying to parse out payload blocks
that we will not be using in the pipeline. 

Good observation on the number of bytes used. In the Egress pipeline, the blk35 is unused -- it brings the total number
of payload bytes stored to 160 bytes. The unused payload block must be a remnant of the refactoring we had done before releasing the code. 

Please feel free to reach out if you have additional questions.

**Comment by rudh24** [comment]
Thanks for the quick response!. Will be in touch should I have more questions.

A minor clarification: I'm assuming, that using the 2 structures with different blk sizes bit<16> bit<32> also happens to be a switch specific decision? Does it somehow relate to how the PHV containers are organized?
